# Generated by Django 2.0 on 2018-01-09 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPattern',
            fields=[
                ('activity_id', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('metropia_id', models.IntegerField(help_text='Unique ID for each Metropia user')),
                ('from_lat', models.FloatField(help_text='Start latitude')),
                ('from_lon', models.FloatField(help_text='Start longitude')),
                ('tp_lat', models.FloatField(help_text='End latitude')),
                ('to_lon', models.FloatField(help_text='End longitude')),
                ('start_time', models.TimeField(help_text='Start time of the activity')),
                ('end_time', models.TimeField(help_text='End time of the activity')),
                ('add_datetime', models.DateTimeField(help_text='Date & time when this activity pattern was added')),
                ('mod_datetime', models.DateTimeField(help_text='Date & time when this activity pattern was last modified')),
                ('travel_plan_update_datetime', models.DateTimeField(help_text='Date & time when travel plans for this activity pattern was updated')),
                ('avail_travel_options', models.TextField(help_text='A list of available travel options for this activity pattern')),
            ],
            options={
                'db_table': 'activity_pattern',
                'get_latest_by': ('travel_plan_update_datetime', 'mod_datetime', 'add_datetime'),
            },
        ),
        migrations.CreateModel(
            name='BikeAndRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('wait_time', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalized_options.ActivityPattern')),
            ],
            options={
                'db_table': 'bike_and_ride',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BikeTransit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('wait_time', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalized_options.ActivityPattern')),
            ],
            options={
                'db_table': 'bike_transit',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Biking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('wait_time', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalized_options.ActivityPattern')),
            ],
            options={
                'db_table': 'biking',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('wait_time', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('congestion_level', models.IntegerField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalized_options.ActivityPattern')),
            ],
            options={
                'db_table': 'driving',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KissAndRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('wait_time', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalized_options.ActivityPattern')),
            ],
            options={
                'db_table': 'kiss_and_ride',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParkAndRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('wait_time', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalized_options.ActivityPattern')),
            ],
            options={
                'db_table': 'park_and_ride',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UberPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('wait_time', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('cost_low', models.IntegerField()),
                ('high_low', models.IntegerField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalized_options.ActivityPattern')),
            ],
            options={
                'db_table': 'uberpool',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UberX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('wait_time', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('cost_low', models.IntegerField()),
                ('high_low', models.IntegerField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalized_options.ActivityPattern')),
            ],
            options={
                'db_table': 'uberx',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UberXL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('wait_time', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('cost_low', models.IntegerField()),
                ('high_low', models.IntegerField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalized_options.ActivityPattern')),
            ],
            options={
                'db_table': 'uberxl',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Walking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('wait_time', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalized_options.ActivityPattern')),
            ],
            options={
                'db_table': 'walking',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalkTransit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('wait_time', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalized_options.ActivityPattern')),
            ],
            options={
                'db_table': 'walk_transit',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='activitypattern',
            index=models.Index(fields=['activity_id'], name='activity_id_idx'),
        ),
    ]
