# Generated by Django 2.0 on 2018-01-09 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_options', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('wait_time', models.IntegerField()),
                ('travel_time', models.IntegerField()),
                ('cost_low', models.IntegerField()),
                ('high_low', models.IntegerField()),
                ('product', models.CharField(max_length=100)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalized_options.ActivityPattern')),
            ],
            options={
                'abstract': False,
                'db_table': 'uber',
            },
        ),
        migrations.RemoveField(
            model_name='uberpool',
            name='activity_id',
        ),
        migrations.RemoveField(
            model_name='uberx',
            name='activity_id',
        ),
        migrations.RemoveField(
            model_name='uberxl',
            name='activity_id',
        ),
        migrations.DeleteModel(
            name='UberPool',
        ),
        migrations.DeleteModel(
            name='UberX',
        ),
        migrations.DeleteModel(
            name='UberXL',
        ),
    ]
