# Generated by Django 2.0 on 2018-01-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_options', '0002_auto_20180109_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitypattern',
            old_name='tp_lat',
            new_name='to_lat',
        ),
    ]
