# Generated by Django 2.0 on 2018-01-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_options', '0002_activitypattern_pattern_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypattern',
            name='add_datetime',
            field=models.DateTimeField(blank=True, help_text='Date & time when this activity pattern was added', null=True),
        ),
    ]
