# Generated by Django 2.0 on 2018-01-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_options', '0004_auto_20180109_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypattern',
            name='mod_datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='Date & time when this activity pattern was last modified'),
        ),
    ]
