# Generated by Django 2.0 on 2018-01-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalized_options', '0005_auto_20180109_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypattern',
            name='avail_travel_options',
            field=models.TextField(blank=True, help_text='A list of available travel options for this activity pattern'),
        ),
        migrations.AlterField(
            model_name='activitypattern',
            name='travel_plan_update_datetime',
            field=models.DateTimeField(blank=True, help_text='Date & time when travel plans for this activity pattern was updated', null=True),
        ),
    ]
